@startebnf

title OpenKNX Universal Config Transfer Serialization Format

UCT_STRING = UCT_HEADER, ("§" (*Single-Line:\nRequired for Import *), {CONFIG_VALUE, "§"} | "\n" (*Multi-Line:\nFor Humans *), {CONFIG_VALUE, "\n"}), UCT_END;

UCT_HEADER = "OpenKNX", ",", VERSION_DEF, ",", CONFIG_PATH;

' VERSION_DEF = "v0", [ ":", SEMVER, [":", GENERATOR]];
VERSION_DEF = "cv0" (* May change in first release! *), [ ":", GENERATOR];

CONFIG_PATH = APP_DEF, "/", MODULE_DEF, "/", CHANNEL_DEF;


APP_DEF = ( "*" | APP_ID, [":", [VERSION] , [ ":" , APP_NAME ](* Not yet included *)] );

MODULE_DEF = MODULE_KEY, [":", VERSION];

CHANNEL_DEF = ("0" (* Base-Config outside of Channel *) | "*" | ?1-99?);

APP_ID  = HEXNUM;

VERSION = ( SEMVER | DECVER | HEXNUM);



HEXNUM = "0x" , {(?0-9? | ?A-F?)}-;

CONFIG_VALUE = PARAM_KEY, "=", PARAM_VALUE;

PARAM_KEY = PARAM_NAME, [":", PARAM_REF_ID];

UCT_END = ";OpenKNX";

/'
digit-excluding-zero = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";
digit                = "0" | digit-excluding-zero;
'/

@endyaml