
on: [push]

jobs:
  ofm-check-job:
    name: Check OFM

    uses: openknx/actions/.github/workflows/openknx-ofm-check.yml@v0
    with:
      # TODO use this as default in action
      # ofm: ${{ github.event.repository.name }}
      # TODO use this as default in action
      # ofm_ref: ${{ github.ref_name }}
      # TODO get this from OFM-repo
      ofm_prefix: UCT
      # TODO get this from OFM-repo
      oam: OAM-StateEngine
      # oam_ref: v1dev
      # knxprod_xml: StateEngine-DFA16-Release
      # TODO get this from OAM-repo
      target: DFA16-Release
      # TODO get this from OAM-repo
      KNXPROD_PREFIX: StateEngine
